---
kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
  - name: installDependencies
    image: node:lts
    commands:
      - npm ci --registry=https://registry.npm.taobao.org

  - name: build
    image: node:lts
    commands:
      - npm run fix-compatibility
      - npm run build
      - tar -czf legacy.tar.gz -C ./dist .
      - npm run build -- --modern
      - tar -czf modern.tar.gz -C ./dist .


  - name: release
    image: plugins/gitea-release
    settings:
      base_url: https://git.ixarea.com
      files:
        - modern.tar.gz
        - legacy.tar.gz
      api_key:
        from_secret: gitea_token
      checksum:
        - sha256
    when:
      event: [tag]

  - name: deploy
    image: plugins/s3
    settings:
      bucket: unlock-music
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: dist/**/*
      strip_prefix: dist/
      target: /public
      path_style: true
      endpoint: https://fs.sz2.ixarea.com


  - name: upload
    image: plugins/s3
    settings:
      bucket: unlock-music
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: ./*.tar.gz
      target: /build/${DRONE_BUILD_NUMBER}
      path_style: true
      endpoint: https://fs.sz2.ixarea.com
